// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/dongwlin/legero-backend/internal/ent/orderitem"
	"github.com/dongwlin/legero-backend/internal/ent/schema"
	"github.com/dongwlin/legero-backend/internal/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	orderitemFields := schema.OrderItem{}.Fields()
	_ = orderitemFields
	// orderitemDescIncludeNoodles is the schema descriptor for include_noodles field.
	orderitemDescIncludeNoodles := orderitemFields[1].Descriptor()
	// orderitem.DefaultIncludeNoodles holds the default value on creation for the include_noodles field.
	orderitem.DefaultIncludeNoodles = orderitemDescIncludeNoodles.Default.(bool)
	// orderitemDescCustomNoodleType is the schema descriptor for custom_noodle_type field.
	orderitemDescCustomNoodleType := orderitemFields[3].Descriptor()
	// orderitem.DefaultCustomNoodleType holds the default value on creation for the custom_noodle_type field.
	orderitem.DefaultCustomNoodleType = orderitemDescCustomNoodleType.Default.(string)
	// orderitemDescExtraNoodleBlocks is the schema descriptor for extra_noodle_blocks field.
	orderitemDescExtraNoodleBlocks := orderitemFields[5].Descriptor()
	// orderitem.DefaultExtraNoodleBlocks holds the default value on creation for the extra_noodle_blocks field.
	orderitem.DefaultExtraNoodleBlocks = orderitemDescExtraNoodleBlocks.Default.(int)
	// orderitemDescCustomSizePrice is the schema descriptor for custom_size_price field.
	orderitemDescCustomSizePrice := orderitemFields[7].Descriptor()
	// orderitem.DefaultCustomSizePrice holds the default value on creation for the custom_size_price field.
	orderitem.DefaultCustomSizePrice = orderitemDescCustomSizePrice.Default.(float64)
	// orderitemDescMeatAvailable is the schema descriptor for meat_available field.
	orderitemDescMeatAvailable := orderitemFields[8].Descriptor()
	// orderitem.DefaultMeatAvailable holds the default value on creation for the meat_available field.
	orderitem.DefaultMeatAvailable = orderitemDescMeatAvailable.Default.([]string)
	// orderitemDescMeatExcluded is the schema descriptor for meat_excluded field.
	orderitemDescMeatExcluded := orderitemFields[9].Descriptor()
	// orderitem.DefaultMeatExcluded holds the default value on creation for the meat_excluded field.
	orderitem.DefaultMeatExcluded = orderitemDescMeatExcluded.Default.([]string)
	// orderitemDescNote is the schema descriptor for note field.
	orderitemDescNote := orderitemFields[16].Descriptor()
	// orderitem.DefaultNote holds the default value on creation for the note field.
	orderitem.DefaultNote = orderitemDescNote.Default.(string)
	// orderitemDescPrice is the schema descriptor for price field.
	orderitemDescPrice := orderitemFields[17].Descriptor()
	// orderitem.DefaultPrice holds the default value on creation for the price field.
	orderitem.DefaultPrice = orderitemDescPrice.Default.(float64)
	// orderitemDescCreatedAt is the schema descriptor for created_at field.
	orderitemDescCreatedAt := orderitemFields[21].Descriptor()
	// orderitem.DefaultCreatedAt holds the default value on creation for the created_at field.
	orderitem.DefaultCreatedAt = orderitemDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescNickname is the schema descriptor for nickname field.
	userDescNickname := userFields[0].Descriptor()
	// user.NicknameValidator is a validator for the "nickname" field. It is called by the builders before save.
	user.NicknameValidator = userDescNickname.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[3].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescPhoneNumber is the schema descriptor for phone_number field.
	userDescPhoneNumber := userFields[4].Descriptor()
	// user.PhoneNumberValidator is a validator for the "phone_number" field. It is called by the builders before save.
	user.PhoneNumberValidator = userDescPhoneNumber.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[7].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[8].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
