// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/dongwlin/legero-backend/internal/handler"
	"github.com/dongwlin/legero-backend/internal/infra/config"
	"github.com/dongwlin/legero-backend/internal/service/v1"
)

// Injectors from wire.go:

// InitializeApplication builds the all-in-one HTTP application.
func InitializeApplication() (*Application, func(), error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, nil, err
	}
	context := ProvideContext()
	db, cleanup, err := ProvideDatabase(context, configConfig)
	if err != nil {
		return nil, nil, err
	}
	location, err := ProvideLocation(configConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	broker := ProvideBroker()
	order := v1.NewOrder(db, location, broker)
	passwordHasher := ProvidePasswordHasher()
	tokenTTL := ProvideTokenTTL(configConfig)
	v := ProvidePasetoKey(configConfig)
	auth, err := ProvideAuth(db, order, passwordHasher, location, tokenTTL, v)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	string2 := ProvideTimezone(configConfig)
	stats := v1.NewStats(db, string2)
	sessionManager := ProvideSessionManager(configConfig)
	logger := ProvideLogger()
	v2 := ProvideNow()
	engine := handler.NewRouter(auth, order, stats, broker, sessionManager, location, configConfig, logger, v2)
	server := ProvideHTTPServer(configConfig, engine)
	application := NewApplication(server)
	return application, func() {
		cleanup()
	}, nil
}

// InitializeUserCreator builds the create-user CLI bootstrap.
func InitializeUserCreator() (*UserCreator, func(), error) {
	context := ProvideContext()
	configConfig, err := config.Load()
	if err != nil {
		return nil, nil, err
	}
	db, cleanup, err := ProvideDatabase(context, configConfig)
	if err != nil {
		return nil, nil, err
	}
	passwordHasher := ProvidePasswordHasher()
	user := v1.NewUser(db, passwordHasher)
	userCreator := NewUserCreator(user)
	return userCreator, func() {
		cleanup()
	}, nil
}
